### ISSUE TITLE
Cell sizing issue on iOS 8 only

### ISSUE THREAD

**Issue by LeChatNoir69** [smileyborg/TableViewCellWithAutoLayout#12]
Hi,

While your project works on iOS7 and iOS8 simulator, I have troubles when using it in my project.

I've made my customCell. It's a copy/paste of yours. The only difference is that my tableView is in a subview.
In iOS7, no problem, it works. With iOS8 simulator, the computed size is good (I've NSLogged the returned "height" of the cell). The cell is well framed but the UILabel inside is stuccoed to 0,0,0,0 !

iOS8 only and I can't figure out what is wrong...

**Comment by winkelsdorf** [comment]
@smileyborg Hi Tyler,

I just stumbled upon this issue here while search for a solution for wrong AutoLayout margins with UITableViewCells. My related question on SO: http://stackoverflow.com/questions/36550417/uilabel-autolayout-ignores-uitableviewcells-left-margin-on-ios-8-1-and-8-2

I tracked it down with a simple test project and Reveal to be really a problem on iOS 8.x side.

The problem was - like LeChatNoir69 said -, **that the calls to `setNeedsUpdateConstraints` and `updateConstraintsIfNeeded` are essential when dequeuing the cell when trying to support iOS 8.0-8.2**, as the Constraints are not updated without when using custom cells.

Could this please get some kind of more prominent attention from the UIKit documentation team? 

There are dozens of threads on SO, each proving "the ultimate solution" (dealing with .layoutMargins, .separatorInsets, playing with preferredMaxWidth for UILabels, overriding layoutSubViews, overriding layoutMarginsDidChange and many more ways) but they all failed.

I had to support iOS 8.0-8.2 in a current project developed in Swift and there was no single official reference to this known bug, please correct me if I'm wrong - at least I was unable to find one (despite some claimed that it's known and confirmed, but knew no recommended official way around).

I find it very difficult having to "reinvent the wheel" with known bugs, because OpenRadar is not sufficient (depends on User's publishing and lacks quality) and there is no official knowledge base about known bugs and how to circumvent them if in need to support an older iOS version (usually current iOS major version -1).

As OpenSource developer providing OpenSSL precompiled libraries, I worked many years with developers of another compiler & ide manufacturer from the Bay Area, and they have a private and public issue tracker (now jira based), so confirmed known bugs and their suggested workarounds were available to the registered developers.

This saves a lot of time, in this case it would have saved about a week to get things right (and not fixed quick and dirty).

Even if this is very likely the wrong place to send a feature request, would love to see something comparable some day. Probably you know somebody to forward this suggestion to :) 

Edit: Sorry, but even this does not work entirely with iOS 8.1 and 8.2. I'll create an issue in your other project https://github.com/smileyborg/TableViewCellWithAutoLayoutiOS8.

Cheers,
Frederik
